import type { Dictionary } from './types'

export const ru: Dictionary = {
  meta: {
    title: 'Скрытые камеры, GPS прослушка и диктофоны в Ташкенте | YASHIRIN CAMERA',
    description:
      'YASHIRIN CAMERA (Скрытая Камера) - надежный сервис с 2013 года. Скрытые мини камеры, GPS прослушка, профессиональные диктофоны и микро наушники оптом и в розницу. Доставка в 98 стран, быстрая установка и настройка. Тел: +998 99 086-99-99',
    keywords: [
      'скрытая камера',
      'мини камера ташкент',
      'gps прослушка',
      'прослушка цена',
      'диктофон ташкент',
      'wifi скрытая камера',
      'микро наушник',
      'gps трекер',
      'yashirin camera',
      'скрытая камера ташкент',
    ],
    ogTitle: 'Скрытые камеры, GPS прослушка и диктофоны в Ташкенте',
    ogDescription:
      'YASHIRIN CAMERA - с 2013 года магазин скрытых мини камер, GPS прослушки и диктофонов. Доставка в 98 стран.',
    siteDescription: 'Интернет-магазин скрытых камер, GPS прослушки, диктофонов и микро наушников',
  },

  a11y: {
    skipToContent: 'Перейти к основному содержанию',
    mainNav: 'Главное меню',
    openMenu: 'Открыть меню',
    langSwitcher: 'Выбор языка сайта',
    switchToUz: 'Переключить на узбекский язык',
    switchToRu: 'Переключить на русский язык',
  },

  nav: {
    catalog: 'Каталог',
    features: 'Как это работает',
    pricing: 'Доставка',
    blog: 'Статьи',
    contact: 'Контакты',
    cart: 'Корзина',
    demo: 'Купить',
  },

  hero: {
    badgeNew: 'Новинка',
    badgeUpdate: 'Поступила GPS прослушка 4G LTE →',
    title: 'Скрытые камеры, GPS прослушка и профессиональные диктофоны.',
    description:
      'YASHIRIN CAMERA - надежный сервис с 2013 года. Более 25 оригинальных моделей, оптом и в розницу, доставка в 98 стран, быстрая установка и настройка.',
    ctaPrimary: 'Купить →',
    ctaSecondary: 'Смотреть каталог →',
    panelAria: 'Вид панели управления скрытой камерой с телефона',
    imageAlt: 'Скрытая мини камера на кончике пальца - YASHIRIN CAMERA Ташкент',
  },

  panel: {
    tabs: ['Камеры', 'Записи', 'Тревоги', 'GPS', 'Настройки'],
    stats: [
      { label: 'МОДЕЛЕЙ В КАТАЛОГЕ', value: '25', change: '+5', up: true },
      { label: 'НА РЫНКЕ', value: '2013', change: 'года', up: true },
      { label: 'ДОСТАВКА', value: '98', change: 'стран', up: true },
      { label: 'ОРИГИНАЛ', value: '100%', change: 'гарантия', up: true },
    ],
    connect: {
      title: 'Подключите устройство к телефону',
      subtitle: 'Поможем связать камеру и GPS прослушку с приложением за минуту.',
      action: 'Подключить',
      rows: [
        { name: 'GPS трекер 4G LTE', sub: 'Приложение XADGPS' },
        { name: 'Wi-Fi мини камера', sub: 'Живая трансляция' },
        { name: 'Профессиональный диктофон', sub: 'Аудиозапись' },
      ],
    },
    chart: { title: 'Популярные разделы', subtitle: 'Скрытые камеры' },
  },

  ticker: {
    note: 'Доставляем по всему Узбекистану через BTS EXPRESS за 1-2 дня',
    items: [
      'Надежный сервис с 2013 года',
      '100% оригинал',
      'Доставка в 98 стран',
      'Без предоплаты',
      'Быстрая установка и настройка',
      'Почта BTS EXPRESS',
      'Оптом и в розницу',
      'Наличные или карта',
      'Заказ через Telegram',
      'Качество гарантировано',
    ],
  },

  features: {
    eyebrow: 'Почему YASHIRIN CAMERA',
    title: 'С 2013 года - от заказа до установки всё просто',
    subtitle:
      'Переводить деньги заранее не нужно. Товар приходит в почтовый офис, вы его осматриваете и только потом оплачиваете. Устройство быстро установим и настроим.',
    steps: {
      title: 'Заказ',
      desc: 'Три шага: вы выбираете, мы отправляем, вы платите после получения.',
      rows: [
        { id: 'ШАГ 1', label: 'Заказ по телефону или через Telegram' },
        { id: 'ШАГ 2', label: 'Отправляем через BTS EXPRESS' },
        { id: 'ШАГ 3', label: 'Быстро установим и настроим' },
      ],
    },
    stat: {
      title: 'Опыт',
      desc: 'Работаем с 2013 года - в каталоге 25 оригинальных моделей, всё есть на складе.',
      label: 'НА РЫНКЕ',
      value: '2013',
      change: 'года',
    },
    create: {
      title: 'Доставка',
      desc: 'По Узбекистану за 1-2 дня через BTS EXPRESS, всего доставляем в 98 стран.',
    },
    sections: {
      title: 'Разделы',
      desc: 'Скрытые камеры, GPS прослушка, диктофоны и микро наушник - всё в одном месте.',
      items: [
        { label: 'Скрытые камеры', depth: 0 },
        { label: 'Wi-Fi модели', depth: 1 },
        { label: 'Розетка и лампа', depth: 1 },
        { label: 'GPS прослушка', depth: 0 },
        { label: 'Диктофоны', depth: 0 },
        { label: 'Микро наушник', depth: 0 },
      ],
    },
  },

  catalog: {
    eyebrow: 'Каталог',
    title: 'Скрытые камеры - 16 разных видов',
    p1: 'В виде розетки, адаптера, лампы, настольных и настенных часов, очков, ручки, кепки, галстука, брелока и пуговицы. Все передают живое видео на телефон по Wi-Fi.',
    p2: 'Не знаете, какая модель подойдет - позвоните или напишите в Telegram, мы подберем.',
    cta: 'Все модели →',
    checks: [
      'Качество 1080P FullHD и 4K UltraHD',
      'Угол обзора 140° и ночное видение',
      'Карта памяти до 128 ГБ',
    ],
    panel: {
      groupTitle: 'Разделы каталога',
      items: [
        { label: 'Скрытые камеры', depth: 0 },
        { label: 'Розетка, адаптер, лампа', depth: 1 },
        { label: 'Часы, очки, ручка', depth: 1 },
        { label: 'GPS прослушка', depth: 0 },
        { label: 'Диктофоны', depth: 0 },
        { label: 'Микро наушник', depth: 0 },
      ],
      features: [
        { name: 'Живая трансляция', desc: 'Смотрите в реальном времени по Wi-Fi' },
        { name: 'Датчик движения', desc: 'Запись начинается при движении' },
        { name: 'Ночное видение', desc: 'Инфракрасный режим - четко и в темноте' },
      ],
    },
  },

  products: {
    eyebrow: 'Популярные товары',
    title: 'Самые покупаемые устройства в Ташкенте',
    subtitle: 'Все цены - актуальные цены магазина. Доставка по Ташкенту 20 000 сум, по регионам через BTS EXPRESS за 1-2 дня.',
    priceFrom: 'Цена',
    order: 'Купить',
    seeAll: 'Все товары (25) →',
    items: [
      {
        id: 'gps-4g-lte',
        image: '/img/products/gps-4g-lte-tracker-proslushka.webp',
        name: 'GPS трекер 4G LTE + прослушка (60 часов)',
        desc: 'Новая модель с процессором SimCom 4G. Влагостойкий корпус, сильный магнит, батарея 3000 мАч - до 60 часов работы. Онлайн-слежение через приложение XADGPS.',
        alt: 'GPS трекер 4G LTE с прослушкой в Ташкенте - YASHIRIN CAMERA',
        price: 650000,
        oldPrice: 950000,
        tag: 'Хит',
        category: 'gps',
        type: 'avto',
      },
      {
        id: 'gps-3000',
        image: '/img/products/gps-tracker-proslushka-3000mah.webp',
        name: 'GPS трекер + прослушка 3000 мАч',
        desc: 'Магнитный влагостойкий корпус, работает с SIM Ucell/UMS/Uzmobile/Beeline. Прослушивание звонком с любого расстояния, онлайн-контроль в приложении AIKA. До 15-30 дней работы.',
        alt: 'GPS трекер с прослушкой 3000 мАч в Ташкенте - YASHIRIN CAMERA',
        price: 850000,
        oldPrice: 980000,
        tag: 'GPS',
        category: 'gps',
        type: 'avto',
      },
      {
        id: 'gps-7000',
        image: '/img/products/gps-tracker-proslushka-3000mah.webp',
        name: 'GPS трекер + прослушка 7000 мАч',
        desc: 'Литиевая батарея 7000 мАч - до 30 дней на одном заряде. Сильный магнит надежно держится на металле, скрыто ставится в автомобиль.',
        alt: 'GPS трекер с прослушкой 7000 мАч в Ташкенте - YASHIRIN CAMERA',
        price: 990000,
        oldPrice: 1600000,
        tag: '30 дней',
        category: 'gps',
        type: 'avto',
      },
      {
        id: 'gps-10000',
        image: '/img/products/gps-tracker-proslushka-10000mah.webp',
        name: 'GPS трекер + прослушка 10 000 мАч',
        desc: 'Самая автономная модель: батарея 10 000 мАч, до 40 дней работы. Онлайн-контроль с телефона или компьютера через приложение AIKA.',
        alt: 'GPS трекер с прослушкой 10000 мАч в Ташкенте - YASHIRIN CAMERA',
        price: 1200000,
        oldPrice: 1600000,
        tag: '40 дней',
        category: 'gps',
        type: 'avto',
      },
      {
        id: '4k-mini-kamera',
        image: '/img/products/4k-ultrahd-wifi-mini-kamera.webp',
        name: 'Мини Wi-Fi камера 4K UltraHD',
        desc: 'Угол обзора 140°, датчик движения, батарея 3000 мА. Живое видео на телефон по Wi-Fi, карта памяти до 128 ГБ.',
        alt: 'Мини wifi камера 4K UltraHD в Ташкенте - YASHIRIN CAMERA',
        price: 850000,
        oldPrice: 1200000,
        tag: '4K',
        category: 'kamera',
        type: 'uy',
      },
      {
        id: 'stol-soat-kamera',
        image: '/img/products/wifi-soat-kamera-1080p-tungi.webp',
        name: 'Часы-камера Wi-Fi 1080P (ночное видение)',
        desc: 'Камера в виде настольных часов: 1080P FullHD, инфракрасное ночное видение, датчик движения, батарея 2400 мА.',
        alt: 'Часы камера Wi-Fi 1080P с ночным видением в Ташкенте - YASHIRIN CAMERA',
        price: 850000,
        oldPrice: 980000,
        tag: 'Ночной режим',
        category: 'kamera',
        type: 'uy',
      },
      {
        id: 'kozoynak-kamera',
        image: '/img/products/kameralik-kozoynak-1080p.webp',
        name: 'Очки со скрытой камерой 1080P FullHD',
        desc: 'Камера 12 Мп встроена так, что её не видно. Видео 1920x1080P, память до 128 ГБ, около 120 минут работы.',
        alt: 'Очки со скрытой камерой 1080P в Ташкенте - YASHIRIN CAMERA',
        price: 1100000,
        oldPrice: 1200000,
        tag: 'Premium',
        category: 'kamera',
        type: 'ofis',
      },
      {
        id: 'brelok-kamera',
        image: '/img/products/brelok-yashirin-kamera-1080p.webp',
        name: 'Брелок-камера скрытая 1080P',
        desc: 'В виде автомобильного брелока: сенсор SONY 12 Мп, видео 1080P 30fps, ночной датчик и детекция движения.',
        alt: 'Скрытая камера в виде брелока 1080P в Ташкенте - YASHIRIN CAMERA',
        price: 750000,
        oldPrice: 880000,
        tag: 'Брелок',
        category: 'kamera',
        type: 'avto',
      },
      {
        id: 'ruchka-kamera',
        image: '/img/products/kameralik-ruchka-1080p.webp',
        name: 'Ручка-камера 1080P FullHD',
        desc: 'Не отличается от обычной ручки: съёмка видео и фото, качество 1080P FullHD, удобно носить в кармане.',
        alt: 'Ручка со скрытой камерой 1080P в Ташкенте - YASHIRIN CAMERA',
        price: 700000,
        oldPrice: 880000,
        tag: 'Переносная',
        category: 'kamera',
        type: 'ofis',
      },
      {
        id: 'tugmacha-kamera',
        image: '/img/products/tugmacha-4k-wifi-kamera.webp',
        name: 'Камера-пуговица 4K Wi-Fi',
        desc: 'Камера в виде пуговицы на одежде. Угол 140°, живая трансляция на телефон по Wi-Fi, датчик движения.',
        alt: 'Скрытая камера пуговица 4K wifi в Ташкенте - YASHIRIN CAMERA',
        price: 750000,
        oldPrice: 880000,
        tag: 'Новинка',
        category: 'kamera',
        type: 'ofis',
      },
      {
        id: 'galstuk-kamera',
        image: '/img/products/galstuk-4k-wifi-kamera.webp',
        name: 'Галстук со скрытой камерой 4K Wi-Fi',
        desc: 'Камера 4K UltraHD, встроенная в галстук. Позволяет незаметно вести запись на встречах и переговорах.',
        alt: 'Галстук со скрытой камерой 4K wifi в Ташкенте - YASHIRIN CAMERA',
        price: 1200000,
        oldPrice: 1500000,
        tag: '4K',
        category: 'kamera',
        type: 'ofis',
      },
      {
        id: 'udinitel-kamera',
        image: '/img/products/udinitel-wifi-kamera-1080p.webp',
        name: 'Удлинитель со скрытой камерой Wi-Fi 1080P',
        desc: 'Камера 1080P FullHD внутри удлинителя - питается от сети, поэтому работает 24/7.',
        alt: 'Удлинитель со скрытой камерой wifi 1080P в Ташкенте - YASHIRIN CAMERA',
        price: 1300000,
        oldPrice: 2500000,
        tag: 'От сети',
        category: 'kamera',
        type: 'uy',
      },
      {
        id: 'adapter-kamera',
        image: '/img/products/adapter-wifi-kamera-1080p.webp',
        name: 'Адаптер со скрытой камерой Wi-Fi 1080P',
        desc: 'Камера в виде зарядного адаптера. Вставляется в розетку и передаёт живое видео на телефон по Wi-Fi.',
        alt: 'Адаптер со скрытой камерой wifi 1080P в Ташкенте - YASHIRIN CAMERA',
        price: 750000,
        oldPrice: 1500000,
        tag: 'Скидка',
        category: 'kamera',
        type: 'uy',
      },
      {
        id: 'rozetka-kamera',
        image: '/img/products/rozetka-wifi-kamera-1080p.webp',
        name: 'Розетка со скрытой камерой Wi-Fi 1080P',
        desc: 'Монтируется в стенную розетку и питается от сети. Качество 1080P FullHD, наблюдение из любой точки по Wi-Fi.',
        alt: 'Розетка со скрытой камерой wifi 1080P в Ташкенте - YASHIRIN CAMERA',
        price: 1200000,
        oldPrice: 1700000,
        tag: '24/7',
        category: 'kamera',
        type: 'uy',
      },
      {
        id: 'tv-pult-kamera',
        image: '/img/products/tv-pult-wifi-kamera.webp',
        name: 'Пульт от телевизора со скрытой камерой Wi-Fi',
        desc: 'Не отличается от обычного пульта. Удобен для контроля дома и офиса, живая трансляция на телефон.',
        alt: 'Пульт от телевизора со скрытой камерой wifi в Ташкенте - YASHIRIN CAMERA',
        price: 990000,
        tag: 'Wi-Fi',
        category: 'kamera',
        type: 'uy',
      },
      {
        id: 'stol-soati-kamera',
        image: '/img/products/stol-soati-wifi-kamera.webp',
        name: 'Скрытая Wi-Fi камера - настольные часы',
        desc: 'Камера в виде будильника: угол 140°, живое видео на телефон по Wi-Fi и оповещение о движении.',
        alt: 'Настольные часы со скрытой wifi камерой в Ташкенте - YASHIRIN CAMERA',
        price: 1000000,
        tag: 'Настольные часы',
        category: 'kamera',
        type: 'uy',
      },
      {
        id: 'lampa-kamera',
        image: '/img/products/lampa-wifi-kamera-1080p.webp',
        name: 'Лампа со скрытой камерой Wi-Fi 1080P',
        desc: 'Вкручивается в обычный патрон, есть датчик движения. Качество 1080P FullHD, постоянное питание от сети.',
        alt: 'Лампа со скрытой камерой wifi 1080P в Ташкенте - YASHIRIN CAMERA',
        price: 850000,
        oldPrice: 2500000,
        tag: 'Скидка',
        category: 'kamera',
        type: 'uy',
      },
      {
        id: 'kepka-kamera',
        image: '/img/products/kepka-wifi-kamera.webp',
        name: 'Кепка со скрытой камерой Wi-Fi',
        desc: 'Камера 4K UltraHD, встроенная в кепку, работает в приложении HDCameraPro. Удобно снимать на ходу.',
        alt: 'Кепка со скрытой камерой wifi в Ташкенте - YASHIRIN CAMERA',
        price: 1200000,
        oldPrice: 1500000,
        tag: 'Кепка',
        category: 'kamera',
        type: 'sayohat',
      },
      {
        id: 'devor-soati-kamera',
        image: '/img/products/devor-soati-wifi-kamera.webp',
        name: 'Скрытая Wi-Fi камера - настенные часы',
        desc: 'Камера внутри настенных часов: угол обзора 140°, незаметное решение для дома и офиса.',
        alt: 'Настенные часы со скрытой wifi камерой в Ташкенте - YASHIRIN CAMERA',
        price: 1200000,
        oldPrice: 1300000,
        tag: 'Настенные часы',
        category: 'kamera',
        type: 'ofis',
      },
      {
        id: 'premium-qol-soati',
        image: '/img/products/premium-kameralik-qol-soati.webp',
        name: 'Наручные часы Premium Class со скрытой камерой',
        desc: 'Премиальные наручные часы с камерой: снимают фото и видео, камера совершенно незаметна.',
        alt: 'Наручные часы со скрытой камерой Premium в Ташкенте - YASHIRIN CAMERA',
        price: 1400000,
        oldPrice: 1900000,
        tag: 'Premium',
        category: 'kamera',
        type: 'sayohat',
      },
      {
        id: 'diktafon-16gb',
        image: '/img/products/professional-mini-diktafon-16gb.webp',
        name: 'Профессиональный мини диктофон 16 ГБ',
        desc: 'Очень компактный, встроенная память 16 ГБ - до 192 часов записи. До 13-15 часов непрерывной записи, наушники в комплекте.',
        alt: 'Профессиональный мини диктофон 16 ГБ в Ташкенте - YASHIRIN CAMERA',
        price: 650000,
        oldPrice: 780000,
        tag: '16 ГБ',
        category: 'diktofon',
        type: 'ofis',
      },
      {
        id: 'usb-diktafon',
        image: '/img/products/usb-fleshka-diktafon-16gb.webp',
        name: 'Диктофон в виде USB флешки 16 ГБ',
        desc: 'Не отличается от обычной флешки: 16 ГБ памяти, 5 часов записи в качестве 192 кбит/с. Файлы слушаются на компьютере.',
        alt: 'Диктофон в виде USB флешки 16 ГБ в Ташкенте - YASHIRIN CAMERA',
        price: 400000,
        oldPrice: 780000,
        tag: 'Выгодно',
        category: 'diktofon',
        type: 'ofis',
      },
      {
        id: 'diktafon-32gb',
        image: '/img/products/professional-diktafon-32gb.webp',
        name: 'Диктофон длительной записи 32 ГБ',
        desc: '32 ГБ памяти и магнитный корпус - крепится к металлу. До 15 дней непрерывной записи на одном заряде.',
        alt: 'Профессиональный диктофон длительной записи 32 ГБ в Ташкенте - YASHIRIN CAMERA',
        price: 800000,
        oldPrice: 1200000,
        tag: '15 дней',
        category: 'diktofon',
        type: 'avto',
      },
      {
        id: 'ovoz-datchikli-diktafon',
        image: '/img/products/ovoz-datchikli-diktafon.webp',
        name: 'Профессиональный диктофон с датчиком звука 16 ГБ',
        desc: 'Включается автоматически при звуке и экономит память в тишине. 16 ГБ памяти, очень чистая запись.',
        alt: 'Профессиональный диктофон с датчиком звука в Ташкенте - YASHIRIN CAMERA',
        price: 700000,
        oldPrice: 1200000,
        tag: 'Датчик звука',
        category: 'diktofon',
        type: 'sayohat',
      },
      {
        id: 'gsm-vip-card',
        image: '/img/products/gsm-vip-card-mikro-naushnik.webp',
        name: 'Микро наушник GSM VIP CARD',
        desc: 'GSM-модуль в виде карты: вставляется SIM и звонок принимается автоматически. Чувствительный микрофон 35 дБ слышит даже шёпот, батарея 650 мАч - 3-5 часов.',
        alt: 'Микро наушник GSM VIP CARD в Ташкенте - YASHIRIN CAMERA',
        price: 850000,
        oldPrice: 1200000,
        tag: 'GSM',
        category: 'naushnik',
        type: 'ofis',
      },
    ],
  },

  detectors: {
    eyebrow: 'GPS прослушка',
    title: 'Следите за автомобилем онлайн и слушайте, что вокруг',
    p1: 'В GPS трекер с прослушкой вставляется SIM-карта. С любого расстояния вы звоните на его номер и слышите звук вокруг, а в приложении AIKA или XADGPS видите местоположение онлайн.',
    p2: 'Сильный магнит и влагостойкий корпус позволяют закрепить устройство даже под автомобилем. Батарея от 3000 до 10 000 мАч - от 60 часов до 40 дней работы.',
    cta: 'Смотреть GPS модели →',
    checks: [
      'Работает с SIM Ucell, Beeline, UMS и Uzmobile',
      'Автономность от 60 часов до 40 дней',
      'Влагостойкий корпус и сильный магнит',
    ],
    panel: {
      features: [
        { name: 'Онлайн-слежение', desc: 'Местоположение на телефоне или компьютере' },
        { name: 'Прослушивание', desc: 'Звоните и слышите звук вокруг' },
        { name: 'Магнитный корпус', desc: 'Надежно держится на металле' },
      ],
      chips: ['GPS + LBS', 'Прослушивание'],
    },
  },

  pricing: {
    eyebrow: 'Доставка',
    title: 'Стоимость доставки и оплата',
    subtitle:
      'Предоплата не нужна. Когда товар придет в офис почты "BTS EXPRESS", вы оплачиваете оператору наличными или пластиковой картой.',
    popular: 'ПОПУЛЯРНЫЙ',
    perKit: 'доставка',
    plans: [
      {
        price: 20000,
        name: 'Город Ташкент',
        desc: 'Быстрая доставка по столице.',
        features: [
          'Доставим в течение 1 дня',
          'Осмотр товара, затем оплата',
          'Наличные или пластиковая карта',
          'Гарантия 100% оригинала',
        ],
        cta: 'Купить',
        highlighted: false,
      },
      {
        price: 25000,
        name: 'Ближние регионы',
        desc: 'Направления Сырдарья, Джизак и Самарканд.',
        features: [
          'Сырдарья - 25 000 сум',
          'Джизак - 30 000 сум',
          'Самарканд - 30 000 сум',
          'За 1-2 дня в офис BTS EXPRESS',
          'Оплата в почтовом офисе',
        ],
        cta: 'Купить',
        highlighted: true,
      },
      {
        price: 35000,
        name: 'Долина и дальние регионы',
        desc: 'Бухара, Навои, Андижан, Наманган, Фергана и другие.',
        features: [
          'Андижан, Наманган, Фергана - 35 000',
          'Бухара, Навои - 35 000 сум',
          'Кашкадарья - 35 000 сум',
          'Сурхандарья - 40 000 сум',
          'Хорезм, Каракалпакстан - 45 000',
        ],
        cta: 'Купить',
        highlighted: false,
      },
    ],
  },

  blog: {
    eyebrow: 'Статьи',
    title: 'Полезные советы по безопасности',
    subtitle:
      'Как выбрать скрытую камеру, как работает GPS прослушка и как проверить помещение - руководства от наших специалистов.',
    readMore: 'Читать далее',
    posts: [
      {
        slug: 'kak-vybrat-skrytuyu-kameru',
        title: 'Как выбрать скрытую камеру: руководство 2026 года',
        tag: 'Руководство',
        excerpt:
          'Разрешение, батарея, Wi-Fi или автономная работа, ночное видение - 7 важных критериев при выборе мини камеры.',
        alt: 'Руководство по выбору скрытой мини камеры - YASHIRIN CAMERA Ташкент',
        image: '/img/products/4k-ultrahd-wifi-mini-kamera.webp',
        author: 'Команда YASHIRIN CAMERA',
        date: '8 августа 2026',
        dateTime: '2026-08-08',
      },
      {
        slug: 'kak-rabotaet-gps-proslushka',
        title: 'Как работает GPS прослушка и куда её можно установить',
        tag: 'GPS',
        excerpt:
          'SIM-карта, магнитный корпус, приложение AIKA и время работы батареи - всё, что нужно знать о GPS трекере с прослушкой.',
        alt: 'Как работает GPS прослушка - YASHIRIN CAMERA Ташкент',
        image: '/img/products/gps-4g-lte-tracker-proslushka.webp',
        author: 'Команда YASHIRIN CAMERA',
        date: '2 августа 2026',
        dateTime: '2026-08-02',
      },
      {
        slug: 'kak-vybrat-diktofon',
        title: 'Как выбрать диктофон: память, время записи и датчик звука',
        tag: 'Диктофон',
        excerpt:
          'Модели на 16 и 32 ГБ, запись от 5 часов до 15 дней - объясняем, какой диктофон подойдет под вашу задачу.',
        alt: 'Совет по выбору профессионального диктофона - YASHIRIN CAMERA',
        image: '/img/products/professional-mini-diktafon-16gb.webp',
        author: 'Команда YASHIRIN CAMERA',
        date: '24 июля 2026',
        dateTime: '2026-07-24',
      },
    ],
  },

  cta: {
    eyebrow: 'Оформить заказ',
    title: 'Не знаете, какая модель вам нужна?',
    desc: 'Позвоните или напишите в Telegram - подберем модель под вашу задачу и назовем цену. По установке и настройке работает отдельная сервисная служба.',
    primary: 'Перейти в магазин →',
    secondary: 'Стоимость доставки',
  },

  shop: {
    meta: {
      title: 'Интернет-магазин - цены на скрытые камеры, GPS прослушку и диктофоны',
      description:
        'Интернет-магазин YASHIRIN CAMERA: 25 моделей с фото и ценами. Доставка по Ташкенту 20 000 сум, по регионам через BTS EXPRESS за 1-2 дня. Оплата после получения.',
      keywords: [
        'купить скрытую камеру',
        'цена мини камеры ташкент',
        'цена gps прослушки',
        'купить диктофон',
        'цена микро наушника',
        'магазин yashirin camera',
      ],
    },
    sidebar: {
      home: 'Главная',
      products: 'Товары',
      productLinks: ['Все товары', 'Каталог', 'Скрытые камеры', 'GPS прослушка', 'Диктофоны'],
      orders: 'Мои заказы',
      payment: 'Оплата и доставка',
      warranty: 'Гарантия',
      support: 'Обслуживание клиентов',
      helpDesk: 'Центр помощи',
      settings: 'Настройки',
      backToSite: 'Вернуться на сайт',
    },
    header: {
      title: 'Каталог товаров',
      subtitle: '25 моделей - с фото и ценой. Добавьте в корзину, и мы свяжемся с вами.',
      searchPlaceholder: 'Поиск товара...',
      userName: 'Покупатель',
      userRole: 'Гость',
    },
    toolbar: {
      breadcrumbRoot: 'Категории',
      breadcrumbCurrent: 'Все цены',
      showingPrefix: 'Всего',
      showingSuffix: 'товаров показано',
      searchPlaceholder: 'Поиск...',
      filter: 'Сортировка',
      cartCta: 'Корзина',
    },
    filters: {
      categories: {
        label: 'Категории',
        all: 'Все категории',
        options: [
          { id: 'kamera', label: 'Скрытые камеры' },
          { id: 'gps', label: 'GPS прослушка' },
          { id: 'diktofon', label: 'Диктофоны' },
          { id: 'naushnik', label: 'Микро наушник' },
        ],
      },
      price: {
        label: 'Цена товара',
        all: 'Все цены',
        options: [
          { id: 'p1', label: 'До 500 000 сум', min: 0, max: 500000 },
          { id: 'p2', label: '500 000 - 800 000 сум', min: 500000, max: 800000 },
          { id: 'p3', label: '800 000 - 1 000 000 сум', min: 800000, max: 1000000 },
          { id: 'p4', label: '1 000 000 - 1 300 000 сум', min: 1000000, max: 1300000 },
          { id: 'p5', label: 'Свыше 1 300 000 сум', min: 1300000, max: 99999999 },
        ],
      },
      rangeLabel: 'Диапазон цены :',
      type: {
        label: 'Где используется',
        all: 'Все варианты',
        options: [
          { id: 'uy', label: 'Дом и квартира' },
          { id: 'ofis', label: 'Офис и магазин' },
          { id: 'avto', label: 'Автомобиль' },
          { id: 'sayohat', label: 'Поездки и отель' },
        ],
      },
      sort: {
        label: 'Сортировка',
        options: [
          { id: 'popular', label: 'Популярные' },
          { id: 'cheap', label: 'Сначала дешевые' },
          { id: 'expensive', label: 'Сначала дорогие' },
          { id: 'name', label: 'По названию' },
        ],
      },
      apply: 'Применить',
      reset: 'Сбросить',
    },
    card: {
      addToCart: 'В корзину',
      added: 'В корзине',
      wishlist: 'Добавить в избранное',
      buy: 'Купить',
      imageSoon: 'Фото скоро',
    },
    cart: {
      title: 'Корзина',
      empty: 'Корзина пока пуста',
      total: 'Итого',
      checkout: 'Заказать через Telegram',
      items: 'товаров',
      remove: 'Удалить',
      close: 'Закрыть',
    },
    empty: {
      title: 'Товары не найдены',
      desc: 'Попробуйте изменить фильтры или сократить поисковый запрос.',
      reset: 'Сбросить фильтры',
    },
  },

  footer: {
    tagline:
      'YASHIRIN CAMERA (Скрытая Камера) - оптом и в розницу с 2013 года. Город Ташкент, Алмазарский район. Скрытые камеры, GPS прослушка, диктофоны и микро наушники.',
    columns: [
      {
        title: 'Каталог',
        links: [
          { label: 'Скрытые камеры', href: '#katalog' },
          { label: 'GPS прослушка', href: '#detektorlar' },
          { label: 'Диктофоны', href: '#mahsulotlar' },
          { label: 'Микро наушник', href: '#mahsulotlar' },
        ],
      },
      {
        title: 'Информация',
        links: [
          { label: 'Доставка', href: '#narxlar' },
          { label: 'Способы оплаты', href: '#narxlar' },
          { label: 'Гарантия', href: '#narxlar' },
          { label: 'Статьи', href: '#maqolalar' },
        ],
      },
      {
        title: 'Помощь',
        links: [
          { label: 'Как оформить заказ', href: '#imkoniyatlar' },
          { label: 'Вопрос-ответ', href: '#maqolalar' },
          { label: 'Магазин', href: '#mahsulotlar' },
          { label: 'Контакты', href: '#aloqa' },
        ],
      },
    ],
    contactsTitle: 'Контакты',
    addressLabel: 'Адрес',
    serviceLabel: 'Сервис (установка и настройка)',
    hours: 'Доставка: по Узбекистану за 1-2 дня, всего в 98 стран',
    rights: 'Все права защищены.',
    legal: ['Политика конфиденциальности', 'Условия использования', 'Политика cookie'],
  },
}
