import type { Dictionary } from './types'

export const uz: Dictionary = {
  meta: {
    title: "Yashirin kamera, GPS proslushka va diktofon Toshkentda | YASHIRIN CAMERA",
    description:
      "YASHIRIN CAMERA - 2013 yildan beri ishonchli xizmat. Yashirin mini kameralar, GPS proslushka, professional diktofon va mikro naushniklar optom va chakana. 98 ta davlatga yetkazib berish, tezkor o'rnatish va sozlash. Tel: +998 99 086-99-99",
    keywords: [
      "yashirin kamera",
      "yashirin camera",
      "mini kamera toshkent",
      "gps proslushka",
      "proslushka narxi",
      "diktofon toshkent",
      "wifi yashirin kamera",
      "mikro naushnik",
      "gps treker",
      "yashirin camera",
    ],
    ogTitle: "Yashirin kamera, GPS proslushka va diktofon Toshkentda",
    ogDescription:
      "YASHIRIN CAMERA - 2013 yildan beri yashirin mini kameralar, GPS proslushka va diktofonlar do'koni. 98 ta davlatga yetkazib beramiz.",
    siteDescription: "Yashirin kameralar, GPS proslushka, diktofon va mikro naushniklar onlayn do'koni",
  },

  a11y: {
    skipToContent: "Asosiy kontentga o'tish",
    mainNav: "Asosiy menyu",
    openMenu: "Menyuni ochish",
    langSwitcher: "Sayt tilini tanlash",
    switchToUz: "O'zbek tiliga o'tish",
    switchToRu: "Rus tiliga o'tish",
  },

  nav: {
    catalog: "Katalog",
    features: "Qanday ishlaydi",
    pricing: "Yetkazib berish",
    blog: "Maqolalar",
    contact: "Aloqa",
    cart: "Savat",
    demo: "Sotib olish",
  },

  hero: {
    badgeNew: "Yangilik",
    badgeUpdate: "4G LTE GPS proslushka keldi →",
    title: "Yashirin Kameralar, GPS Proslushka va Professional Diktofonlar.",
    description:
      "YASHIRIN CAMERA - 2013 yildan beri ishonchli xizmat. 25 dan ortiq original model, optom va chakana savdo, 98 ta davlatga yetkazib berish, tezkor o'rnatish va sozlash.",
    ctaPrimary: "Sotib olish →",
    ctaSecondary: "Katalogni ko'rish →",
    panelAria: "Yashirin kamerani telefondan boshqarish paneli ko'rinishi",
    imageAlt: "Barmoq uchidagi yashirin mini kamera - YASHIRIN CAMERA Toshkent",
  },

  panel: {
    tabs: ["Kameralar", "Yozuvlar", "Signallar", "GPS", "Sozlamalar"],
    stats: [
      { label: "KATALOGDA MODEL", value: "25", change: "+5", up: true },
      { label: "BOZORDA", value: "2013", change: "yildan", up: true },
      { label: "YETKAZIB BERISH", value: "98", change: "davlat", up: true },
      { label: "ORIGINAL", value: "100%", change: "kafolat", up: true },
    ],
    connect: {
      title: "Qurilmani telefoningizga ulang",
      subtitle: "Kamera va GPS proslushkani bir daqiqada ilovaga bog'lab beramiz.",
      action: "Ulash",
      rows: [
        { name: "4G LTE GPS treker", sub: "XADGPS ilova" },
        { name: "Wi-Fi mini kamera", sub: "Jonli efir" },
        { name: "Professional diktofon", sub: "Ovoz yozish" },
      ],
    },
    chart: { title: "Ommabop bo'limlar", subtitle: "Yashirin kamera" },
  },

  ticker: {
    note: "O'zbekiston bo'ylab BTS EXPRESS orqali 1-2 kun ichida yetkazib beramiz",
    items: [
      "2013 yildan beri ishonchli xizmat",
      "100% original mahsulot",
      "98 ta davlatga yetkazib berish",
      "Oldindan to'lovsiz",
      "Tezkor o'rnatish va sozlash",
      "BTS EXPRESS pochta",
      "Optom va chakana savdo",
      "Naqd yoki plastik karta",
      "Telegram orqali buyurtma",
      "Sifat kafolatlangan",
    ],
  },

  features: {
    eyebrow: "Nima uchun YASHIRIN CAMERA",
    title: "2013 yildan beri - buyurtmadan o'rnatishgacha hammasi oddiy",
    subtitle:
      "Oldindan pul o'tkazish shart emas. Tovar pochta ofisiga yetib borgach, ko'rib chiqasiz va shundan keyin to'laysiz. Qurilmani tezkor o'rnatib, sozlab beramiz.",
    steps: {
      title: "Buyurtma",
      desc: "Uch qadam: siz tanlaysiz, biz jo'natamiz, olgach to'laysiz.",
      rows: [
        { id: "1-QADAM", label: "Telefon yoki Telegram orqali buyurtma" },
        { id: "2-QADAM", label: "BTS EXPRESS orqali jo'natamiz" },
        { id: "3-QADAM", label: "Tezkor o'rnatib, sozlab beramiz" },
      ],
    },
    stat: {
      title: "Tajriba",
      desc: "2013 yildan beri ishlaymiz - katalogda 25 ta original model, barchasi omborda.",
      label: "BOZORDA",
      value: "2013",
      change: "yildan",
    },
    create: {
      title: "Yetkazib berish",
      desc: "O'zbekiston bo'ylab BTS EXPRESS orqali 1-2 kunda, jami 98 ta davlatga jo'natamiz.",
    },
    sections: {
      title: "Bo'limlar",
      desc: "Yashirin kameralar, GPS proslushka, diktofonlar va mikro naushnik - hammasi bitta joyda.",
      items: [
        { label: "Yashirin kameralar", depth: 0 },
        { label: "Wi-Fi modellar", depth: 1 },
        { label: "Rozetka va lampa", depth: 1 },
        { label: "GPS proslushka", depth: 0 },
        { label: "Diktofonlar", depth: 0 },
        { label: "Mikro naushnik", depth: 0 },
      ],
    },
  },

  catalog: {
    eyebrow: "Katalog",
    title: "Yashirin kameralar - 16 xil ko'rinishda",
    p1: "Rozetka, adapter, lampa, stol va devor soati, ko'zoynak, ruchka, kepka, galstuk, brelok va tugmacha ko'rinishida. Barchasi Wi-Fi orqali telefoningizga jonli video uzatadi.",
    p2: "Qaysi model sizga mos kelishini bilmasangiz - qo'ng'iroq qiling yoki Telegram orqali yozing, biz tanlab beramiz.",
    cta: "Barcha modellar →",
    checks: [
      "1080P FullHD va 4K UltraHD sifat",
      "140 daraja keng burchak va tungi ko'rish",
      "128 GB gacha xotira kartasi tushadi",
    ],
    panel: {
      groupTitle: "Katalog bo'limlari",
      items: [
        { label: "Yashirin kameralar", depth: 0 },
        { label: "Rozetka, adapter, lampa", depth: 1 },
        { label: "Soat, ko'zoynak, ruchka", depth: 1 },
        { label: "GPS proslushka", depth: 0 },
        { label: "Diktofonlar", depth: 0 },
        { label: "Mikro naushnik", depth: 0 },
      ],
      features: [
        { name: "Jonli efir", desc: "Wi-Fi orqali telefonda real vaqtda ko'rasiz" },
        { name: "Harakat datchigi", desc: "Harakat sezilganda yozuv boshlanadi" },
        { name: "Tungi ko'rish", desc: "Infraqizil rejim - qorong'uda ham aniq" },
      ],
    },
  },

  products: {
    eyebrow: "Ommabop mahsulotlar",
    title: "Toshkentda eng ko'p sotib olinadigan qurilmalar",
    subtitle: "Barcha narxlar do'kondagi joriy narxlar. Toshkent bo'ylab yetkazib berish 20 000 so'm, viloyatlarga BTS EXPRESS orqali 1-2 kunda.",
    priceFrom: "Narxi",
    order: "Sotib olish",
    seeAll: "Barcha mahsulotlar (25) →",
    items: [
      {
        id: "gps-4g-lte",
        image: "/img/products/gps-4g-lte-tracker-proslushka.webp",
        name: "4G LTE GPS treker + proslushka (60 soat)",
        desc: "SimCom 4G protsessorli yangi model. Suvga chidamli korpus, kuchli magnit, 3000 mAh batareya - to'liq quvvatda 60 soat ishlaydi. XADGPS ilovasi orqali onlayn kuzatuv.",
        alt: "4G LTE GPS treker va proslushka Toshkentda - YASHIRIN CAMERA",
        price: 650000,
        oldPrice: 950000,
        tag: "Hit",
        category: "gps",
        type: "avto",
      },
      {
        id: "gps-3000",
        image: "/img/products/gps-tracker-proslushka-3000mah.webp",
        name: "GPS treker + proslushka 3000 mAh",
        desc: "Magnitli suvga chidamli korpus, Ucell/UMS/Uzmobile/Beeline SIM kartalari tushadi. Cheklanmagan masofadan qo'ng'iroq qilib eshitish, AIKA ilovasida onlayn kuzatuv. 15-30 kun ishlaydi.",
        alt: "GPS treker proslushka 3000 mAh Toshkentda - YASHIRIN CAMERA",
        price: 850000,
        oldPrice: 980000,
        tag: "GPS",
        category: "gps",
        type: "avto",
      },
      {
        id: "gps-7000",
        image: "/img/products/gps-tracker-proslushka-3000mah.webp",
        name: "GPS treker + proslushka 7000 mAh",
        desc: "7000 mAh litiy batareya - to'liq quvvatda 30 kun. Kuchli magnit metall yuzaga mahkam yopishadi, mashinaga yashirin o'rnatiladi.",
        alt: "GPS treker proslushka 7000 mAh Toshkentda - YASHIRIN CAMERA",
        price: 990000,
        oldPrice: 1600000,
        tag: "30 kun",
        category: "gps",
        type: "avto",
      },
      {
        id: "gps-10000",
        image: "/img/products/gps-tracker-proslushka-10000mah.webp",
        name: "GPS treker + proslushka 10 000 mAh",
        desc: "Eng uzoq ishlaydigan model: 10 000 mAh batareya bilan 40 kun. AIKA ilovasi orqali telefon yoki kompyuterdan onlayn kuzatib borasiz.",
        alt: "GPS treker proslushka 10000 mAh Toshkentda - YASHIRIN CAMERA",
        price: 1200000,
        oldPrice: 1600000,
        tag: "40 kun",
        category: "gps",
        type: "avto",
      },
      {
        id: "4k-mini-kamera",
        image: "/img/products/4k-ultrahd-wifi-mini-kamera.webp",
        name: "4K UltraHD Wi-Fi mini kamera",
        desc: "140 daraja keng burchak, harakat datchigi, 3000 mA batareya. Wi-Fi orqali telefondan jonli video, 128 GB gacha xotira kartasi tushadi.",
        alt: "4K UltraHD wifi mini yashirin kamera Toshkentda - YASHIRIN CAMERA",
        price: 850000,
        oldPrice: 1200000,
        tag: "4K",
        category: "kamera",
        type: "uy",
      },
      {
        id: "stol-soat-kamera",
        image: "/img/products/wifi-soat-kamera-1080p-tungi.webp",
        name: "Wi-Fi soat-kamera 1080P (tungi ko'rish)",
        desc: "Stol soati ko'rinishidagi kamera: 1080P FullHD, infraqizil tungi ko'rish, harakat datchigi va 2400 mA batareya.",
        alt: "Wi-Fi soat kamera 1080P tungi korish Toshkentda - YASHIRIN CAMERA",
        price: 850000,
        oldPrice: 980000,
        tag: "Tungi rejim",
        category: "kamera",
        type: "uy",
      },
      {
        id: "kozoynak-kamera",
        image: "/img/products/kameralik-kozoynak-1080p.webp",
        name: "Kameralik ko'zoynak 1080P FullHD",
        desc: "12 Mp kamera ko'zoynakka shunday joylashtirilganki, borligi bilinmaydi. Video 1920x1080P, 128 GB gacha xotira, taxminan 120 daqiqa ish vaqti.",
        alt: "Yashirin kameralik kozoynak 1080P Toshkentda - YASHIRIN CAMERA",
        price: 1100000,
        oldPrice: 1200000,
        tag: "Premium",
        category: "kamera",
        type: "ofis",
      },
      {
        id: "brelok-kamera",
        image: "/img/products/brelok-yashirin-kamera-1080p.webp",
        name: "Avto brelok yashirin kamera 1080P",
        desc: "Avtomobil pulti ko'rinishida: 12 Mp SONY sensor, 1080P 30fps video, tungi datchik va harakatni sezish funksiyasi.",
        alt: "Brelok korinishidagi yashirin kamera 1080P Toshkentda - YASHIRIN CAMERA",
        price: 750000,
        oldPrice: 880000,
        tag: "Brelok",
        category: "kamera",
        type: "avto",
      },
      {
        id: "ruchka-kamera",
        image: "/img/products/kameralik-ruchka-1080p.webp",
        name: "Kameralik ruchka 1080P FullHD",
        desc: "Oddiy ruchkadan farq qilmaydi: video va foto olish funksiyasi, 1080P FullHD sifat, cho'ntakda olib yurish qulay.",
        alt: "Yashirin kameralik ruchka 1080P Toshkentda - YASHIRIN CAMERA",
        price: 700000,
        oldPrice: 880000,
        tag: "Ko'chma",
        category: "kamera",
        type: "ofis",
      },
      {
        id: "tugmacha-kamera",
        image: "/img/products/tugmacha-4k-wifi-kamera.webp",
        name: "Tugmacha ko'rinishidagi 4K Wi-Fi kamera",
        desc: "Kiyim tugmasi ko'rinishidagi kamera. 140 daraja keng burchak, Wi-Fi orqali telefonda jonli efir, harakat datchigi.",
        alt: "Tugmacha korinishidagi 4K wifi yashirin kamera Toshkentda - YASHIRIN CAMERA",
        price: 750000,
        oldPrice: 880000,
        tag: "Yangi",
        category: "kamera",
        type: "ofis",
      },
      {
        id: "galstuk-kamera",
        image: "/img/products/galstuk-4k-wifi-kamera.webp",
        name: "Galstuk ko'rinishidagi 4K Wi-Fi kamera",
        desc: "Galstuk ichiga o'rnatilgan 4K UltraHD kamera. Uchrashuv va muzokaralarda sezilmasdan yozib olish imkonini beradi.",
        alt: "Galstuk korinishidagi 4K wifi yashirin kamera Toshkentda - YASHIRIN CAMERA",
        price: 1200000,
        oldPrice: 1500000,
        tag: "4K",
        category: "kamera",
        type: "ofis",
      },
      {
        id: "udinitel-kamera",
        image: "/img/products/udinitel-wifi-kamera-1080p.webp",
        name: "Udlinitel ko'rinishidagi Wi-Fi kamera 1080P",
        desc: "Uzaytirgich ichidagi 1080P FullHD kamera - tarmoqdan doimiy quvvat oladi, shuning uchun 24/7 ishlaydi.",
        alt: "Udlinitel korinishidagi wifi yashirin kamera 1080P Toshkentda - YASHIRIN CAMERA",
        price: 1300000,
        oldPrice: 2500000,
        tag: "Doimiy quvvat",
        category: "kamera",
        type: "uy",
      },
      {
        id: "adapter-kamera",
        image: "/img/products/adapter-wifi-kamera-1080p.webp",
        name: "Adapter ko'rinishidagi Wi-Fi kamera 1080P",
        desc: "Telefon zaryadlagichi ko'rinishidagi kamera. Rozetkaga tiqib qo'yiladi va Wi-Fi orqali telefonga jonli video uzatadi.",
        alt: "Adapter korinishidagi wifi yashirin kamera 1080P Toshkentda - YASHIRIN CAMERA",
        price: 750000,
        oldPrice: 1500000,
        tag: "Chegirma",
        category: "kamera",
        type: "uy",
      },
      {
        id: "rozetka-kamera",
        image: "/img/products/rozetka-wifi-kamera-1080p.webp",
        name: "Rozetka ko'rinishidagi Wi-Fi kamera 1080P",
        desc: "Devordagi rozetkaga o'rnatiladi va tarmoqdan quvvat oladi. 1080P FullHD sifat, Wi-Fi orqali istalgan joydan kuzatuv.",
        alt: "Rozetka korinishidagi wifi yashirin kamera 1080P Toshkentda - YASHIRIN CAMERA",
        price: 1200000,
        oldPrice: 1700000,
        tag: "24/7",
        category: "kamera",
        type: "uy",
      },
      {
        id: "tv-pult-kamera",
        image: "/img/products/tv-pult-wifi-kamera.webp",
        name: "Televizor pulti ko'rinishidagi Wi-Fi kamera",
        desc: "Oddiy TV pultidan farq qilmaydi. Uy va ofis xavfsizligini nazorat qilish uchun qulay, telefonda jonli efir.",
        alt: "TV pulti korinishidagi wifi yashirin kamera Toshkentda - YASHIRIN CAMERA",
        price: 990000,
        tag: "Wi-Fi",
        category: "kamera",
        type: "uy",
      },
      {
        id: "stol-soati-kamera",
        image: "/img/products/stol-soati-wifi-kamera.webp",
        name: "Wi-Fi yashirin kamera - stol soati",
        desc: "Budilnik ko'rinishidagi kamera: 140 daraja burchak, Wi-Fi orqali telefondan jonli video va harakat signali.",
        alt: "Stol soati korinishidagi wifi yashirin kamera Toshkentda - YASHIRIN CAMERA",
        price: 1000000,
        tag: "Stol soati",
        category: "kamera",
        type: "uy",
      },
      {
        id: "lampa-kamera",
        image: "/img/products/lampa-wifi-kamera-1080p.webp",
        name: "Lampa ko'rinishidagi Wi-Fi kamera 1080P",
        desc: "Oddiy lampa patroniga o'rnatiladi, harakat datchigi bor. 1080P FullHD sifat, tarmoqdan doimiy quvvat.",
        alt: "Lampa korinishidagi wifi yashirin kamera 1080P Toshkentda - YASHIRIN CAMERA",
        price: 850000,
        oldPrice: 2500000,
        tag: "Chegirma",
        category: "kamera",
        type: "uy",
      },
      {
        id: "kepka-kamera",
        image: "/img/products/kepka-wifi-kamera.webp",
        name: "Kepka ko'rinishidagi Wi-Fi kamera",
        desc: "Bosh kiyimga o'rnatilgan 4K UltraHD kamera, HDCameraPro ilovasida ishlaydi. Yurgan holda yozib olish uchun qulay.",
        alt: "Kepka korinishidagi wifi yashirin kamera Toshkentda - YASHIRIN CAMERA",
        price: 1200000,
        oldPrice: 1500000,
        tag: "Kepka",
        category: "kamera",
        type: "sayohat",
      },
      {
        id: "devor-soati-kamera",
        image: "/img/products/devor-soati-wifi-kamera.webp",
        name: "Wi-Fi yashirin kamera - devor soati",
        desc: "Devor soati ichidagi kamera: 140 daraja keng burchak, uy va ofis xavfsizligi uchun sezilmas yechim.",
        alt: "Devor soati korinishidagi wifi yashirin kamera Toshkentda - YASHIRIN CAMERA",
        price: 1200000,
        oldPrice: 1300000,
        tag: "Devor soati",
        category: "kamera",
        type: "ofis",
      },
      {
        id: "premium-qol-soati",
        image: "/img/products/premium-kameralik-qol-soati.webp",
        name: "Premium Class kameralik qo'l soati",
        desc: "Chinakam qo'l soati ko'rinishidagi premium kamera: foto va video oladi, kamera borligi umuman sezilmaydi.",
        alt: "Premium kameralik qol soati Toshkentda - YASHIRIN CAMERA",
        price: 1400000,
        oldPrice: 1900000,
        tag: "Premium",
        category: "kamera",
        type: "sayohat",
      },
      {
        id: "diktafon-16gb",
        image: "/img/products/professional-mini-diktafon-16gb.webp",
        name: "Professional mini diktofon 16 GB",
        desc: "Juda kichik hajmda, 16 GB o'z xotirasi - 192 soat yozuv. Bir zaryadda 13-15 soat to'xtovsiz yozadi, komplektida naushnik bor.",
        alt: "Professional mini diktofon 16 GB Toshkentda - YASHIRIN CAMERA",
        price: 650000,
        oldPrice: 780000,
        tag: "16 GB",
        category: "diktofon",
        type: "ofis",
      },
      {
        id: "usb-diktafon",
        image: "/img/products/usb-fleshka-diktafon-16gb.webp",
        name: "USB fleshka ko'rinishidagi diktofon 16 GB",
        desc: "Oddiy fleshkadan farq qilmaydi: 16 GB xotira, 192 kbps sifatda 5 soat yozuv. Fayllarni kompyuterda tinglash mumkin.",
        alt: "USB fleshka korinishidagi diktofon 16 GB Toshkentda - YASHIRIN CAMERA",
        price: 400000,
        oldPrice: 780000,
        tag: "Arzon",
        category: "diktofon",
        type: "ofis",
      },
      {
        id: "diktafon-32gb",
        image: "/img/products/professional-diktafon-32gb.webp",
        name: "Uzoq yozuvchi professional diktofon 32 GB",
        desc: "32 GB xotira va magnitli korpus - metall yuzaga yopishadi. Bir zaryadda 15 kun to'xtovsiz ovoz yozadi.",
        alt: "Uzoq vaqt yozuvchi professional diktofon 32 GB Toshkentda - YASHIRIN CAMERA",
        price: 800000,
        oldPrice: 1200000,
        tag: "15 kun",
        category: "diktofon",
        type: "avto",
      },
      {
        id: "ovoz-datchikli-diktafon",
        image: "/img/products/ovoz-datchikli-diktafon.webp",
        name: "Ovoz datchikli professional diktofon 16 GB",
        desc: "Ovoz eshitilganda avtomatik yoqiladi va jimlikda xotirani tejaydi. 16 GB xotira, juda tiniq yozuv sifati.",
        alt: "Ovoz datchikli professional diktofon Toshkentda - YASHIRIN CAMERA",
        price: 700000,
        oldPrice: 1200000,
        tag: "Ovoz datchigi",
        category: "diktofon",
        type: "sayohat",
      },
      {
        id: "gsm-vip-card",
        image: "/img/products/gsm-vip-card-mikro-naushnik.webp",
        name: "GSM VIP CARD mikro naushnik",
        desc: "Karta ko'rinishidagi GSM modul: SIM karta solinadi va qo'ng'iroqni avtomatik qabul qiladi. 35 dB sezgir mikrofon pichirlashni ham eshitadi, 650 mAh batareya 3-5 soat ishlaydi.",
        alt: "GSM VIP CARD mikro naushnik Toshkentda - YASHIRIN CAMERA",
        price: 850000,
        oldPrice: 1200000,
        tag: "GSM",
        category: "naushnik",
        type: "ofis",
      },
    ],
  },

  detectors: {
    eyebrow: "GPS proslushka",
    title: "Mashinangizni onlayn kuzating va atrofdagi ovozni eshiting",
    p1: "GPS treker + proslushkaga SIM karta solinadi. Istalgan masofadan raqamiga qo'ng'iroq qilib atrofdagi ovozni eshitasiz, AIKA yoki XADGPS ilovasida esa joylashuvni onlayn kuzatasiz.",
    p2: "Kuchli magnit va suvga chidamli korpus tufayli mashina ostiga ham o'rnatish mumkin. Batareya 3000 mAh dan 10 000 mAh gacha - 60 soatdan 40 kungacha ishlaydi.",
    cta: "GPS modellarni ko'rish →",
    checks: [
      "Ucell, Beeline, UMS va Uzmobile SIM kartalari tushadi",
      "60 soatdan 40 kungacha avtonom ishlash",
      "Suvga chidamli korpus va kuchli magnit",
    ],
    panel: {
      features: [
        { name: "Onlayn kuzatuv", desc: "Telefon yoki kompyuterda joylashuvni ko'rasiz" },
        { name: "Ovoz eshitish", desc: "Qo'ng'iroq qilib atrofni tinglaysiz" },
        { name: "Magnitli korpus", desc: "Metall yuzaga mahkam yopishadi" },
      ],
      chips: ["GPS + LBS", "Ovoz eshitish"],
    },
  },

  pricing: {
    eyebrow: "Yetkazib berish",
    title: "Yetkazib berish narxlari va to'lov",
    subtitle:
      "Oldindan to'lov qilish shart emas. Tovar \"BTS EXPRESS\" pochta ofisiga yetib borgach, operatorga naqd yoki plastik karta orqali to'laysiz.",
    popular: "OMMABOP",
    perKit: "yetkazish",
    plans: [
      {
        price: 20000,
        name: "Toshkent shahri",
        desc: "Poytaxt bo'ylab tezkor yetkazib berish.",
        features: [
          "1 kun ichida yetkazamiz",
          "Tovarni ko'rib, keyin to'lash",
          "Naqd yoki plastik karta",
          "100% original kafolat",
        ],
        cta: "Sotib olish",
        highlighted: false,
      },
      {
        price: 25000,
        name: "Yaqin viloyatlar",
        desc: "Sirdaryo, Jizzax va Samarqand yo'nalishlari.",
        features: [
          "Sirdaryo - 25 000 so'm",
          "Jizzax - 30 000 so'm",
          "Samarqand - 30 000 so'm",
          "1-2 kunda BTS EXPRESS ofisiga",
          "Pochta ofisida to'lov",
        ],
        cta: "Sotib olish",
        highlighted: true,
      },
      {
        price: 35000,
        name: "Vodiy va uzoq hududlar",
        desc: "Buxoro, Navoiy, Andijon, Namangan, Farg'ona va boshqalar.",
        features: [
          "Andijon, Namangan, Farg'ona - 35 000",
          "Buxoro, Navoiy - 35 000 so'm",
          "Qashqadaryo - 35 000 so'm",
          "Surxondaryo - 40 000 so'm",
          "Xorazm, Qoraqalpog'iston - 45 000",
        ],
        cta: "Sotib olish",
        highlighted: false,
      },
    ],
  },

  blog: {
    eyebrow: "Maqolalar",
    title: "Xavfsizlik bo'yicha foydali maslahatlar",
    subtitle:
      "Yashirin kamerani qanday tanlash, GPS proslushka qanday ishlaydi va xonani qanday tekshirish kerak - mutaxassislarimizdan qo'llanmalar.",
    readMore: "Batafsil o'qish",
    posts: [
      {
        slug: "yashirin-kamera-qanday-tanlanadi",
        title: "Yashirin kamerani qanday tanlash kerak: 2026-yil qo'llanmasi",
        tag: "Qo'llanma",
        excerpt:
          "Aniqlik, batareya, Wi-Fi yoki avtonom, tungi ko'rish - mini kamera tanlashda e'tibor beriladigan 7 ta muhim mezon.",
        alt: "Yashirin mini kamera tanlash bo'yicha qo'llanma - YASHIRIN CAMERA Toshkent",
        image: "/img/products/4k-ultrahd-wifi-mini-kamera.webp",
        author: "YASHIRIN CAMERA jamoasi",
        date: "8-avgust, 2026",
        dateTime: "2026-08-08",
      },
      {
        slug: "gps-proslushka-qanday-ishlaydi",
        title: "GPS proslushka qanday ishlaydi va uni qayerga o'rnatish mumkin",
        tag: "GPS",
        excerpt:
          "SIM karta, magnitli korpus, AIKA ilovasi va batareya muddati - GPS treker + proslushka haqida bilishingiz kerak bo'lgan hamma narsa.",
        alt: "GPS proslushka qanday ishlaydi - YASHIRIN CAMERA Toshkent",
        image: "/img/products/gps-4g-lte-tracker-proslushka.webp",
        author: "YASHIRIN CAMERA jamoasi",
        date: "2-avgust, 2026",
        dateTime: "2026-08-02",
      },
      {
        slug: "diktofon-tanlash",
        title: "Diktofon tanlash: xotira, yozuv muddati va ovoz datchigi",
        tag: "Diktofon",
        excerpt:
          "16 GB va 32 GB modellar, 5 soatdan 15 kungacha yozuv - qaysi diktofon sizning vazifangizga mos kelishini tushuntiramiz.",
        alt: "Professional diktofon tanlash bo'yicha maslahat - YASHIRIN CAMERA",
        image: "/img/products/professional-mini-diktafon-16gb.webp",
        author: "YASHIRIN CAMERA jamoasi",
        date: "24-iyul, 2026",
        dateTime: "2026-07-24",
      },
    ],
  },

  cta: {
    eyebrow: "Buyurtma berish",
    title: "Qaysi model kerakligini bilmayapsizmi?",
    desc: "Qo'ng'iroq qiling yoki Telegram orqali yozing - ehtiyojingizga mos modelni tanlab, narxini aytamiz. O'rnatish va sozlash bo'yicha alohida servis xizmatimiz bor.",
    primary: "Do'konga o'tish →",
    secondary: "Yetkazib berish narxi",
  },

  shop: {
    meta: {
      title: "Onlayn do'kon - yashirin kamera, GPS proslushka va diktofon narxlari",
      description:
        "YASHIRIN CAMERA onlayn do'koni: 25 ta model, rasmi va narxi bilan. Toshkent bo'ylab 20 000 so'm, viloyatlarga BTS EXPRESS orqali 1-2 kunda. To'lov tovarni olgandan keyin.",
      keywords: [
        "yashirin kamera sotib olish",
        "mini kamera narxi toshkent",
        "gps proslushka narxi",
        "diktofon sotib olish",
        "mikro naushnik narxi",
        "yashirin camera do'kon",
      ],
    },
    sidebar: {
      home: "Bosh sahifa",
      products: "Mahsulotlar",
      productLinks: ["Barcha mahsulotlar", "Katalog", "Yashirin kameralar", "GPS proslushka", "Diktofonlar"],
      orders: "Buyurtmalarim",
      payment: "To'lov va yetkazish",
      warranty: "Kafolat",
      support: "Mijozlarga xizmat",
      helpDesk: "Yordam markazi",
      settings: "Sozlamalar",
      backToSite: "Saytga qaytish",
    },
    header: {
      title: "Mahsulotlar katalogi",
      subtitle: "25 ta model - rasmi va narxi bilan. Savatga qo'shing, biz siz bilan bog'lanamiz.",
      searchPlaceholder: "Mahsulot qidirish...",
      userName: "Xaridor",
      userRole: "Mehmon",
    },
    toolbar: {
      breadcrumbRoot: "Kategoriyalar",
      breadcrumbCurrent: "Barcha narxlar",
      showingPrefix: "Jami",
      showingSuffix: "ta mahsulot ko'rsatilmoqda",
      searchPlaceholder: "Qidirish...",
      filter: "Saralash",
      cartCta: "Savat",
    },
    filters: {
      categories: {
        label: "Kategoriyalar",
        all: "Barcha kategoriyalar",
        options: [
          { id: "kamera", label: "Yashirin kameralar" },
          { id: "gps", label: "GPS proslushka" },
          { id: "diktofon", label: "Diktofonlar" },
          { id: "naushnik", label: "Mikro naushnik" },
        ],
      },
      price: {
        label: "Mahsulot narxi",
        all: "Barcha narxlar",
        options: [
          { id: "p1", label: "500 000 so'mgacha", min: 0, max: 500000 },
          { id: "p2", label: "500 000 - 800 000 so'm", min: 500000, max: 800000 },
          { id: "p3", label: "800 000 - 1 000 000 so'm", min: 800000, max: 1000000 },
          { id: "p4", label: "1 000 000 - 1 300 000 so'm", min: 1000000, max: 1300000 },
          { id: "p5", label: "1 300 000 so'mdan yuqori", min: 1300000, max: 99999999 },
        ],
      },
      rangeLabel: "Narx oralig'i :",
      type: {
        label: "Qayerda ishlatiladi",
        all: "Barcha holatlar",
        options: [
          { id: "uy", label: "Uy va kvartira" },
          { id: "ofis", label: "Ofis va do'kon" },
          { id: "avto", label: "Avtomobil" },
          { id: "sayohat", label: "Sayohat va mehmonxona" },
        ],
      },
      sort: {
        label: "Saralash",
        options: [
          { id: "popular", label: "Ommabop" },
          { id: "cheap", label: "Avval arzoni" },
          { id: "expensive", label: "Avval qimmati" },
          { id: "name", label: "Nomi bo'yicha" },
        ],
      },
      apply: "Qo'llash",
      reset: "Tozalash",
    },
    card: {
      addToCart: "Savatga qo'shish",
      added: "Savatda",
      wishlist: "Saqlanganlarga qo'shish",
      buy: "Sotib olish",
      imageSoon: "Rasm tez orada",
    },
    cart: {
      title: "Savat",
      empty: "Savat hozircha bo'sh",
      total: "Jami",
      checkout: "Telegram orqali buyurtma",
      items: "ta mahsulot",
      remove: "O'chirish",
      close: "Yopish",
    },
    empty: {
      title: "Mahsulot topilmadi",
      desc: "Filtrlarni o'zgartirib ko'ring yoki qidiruv so'zini qisqartiring.",
      reset: "Filtrlarni tozalash",
    },
  },

  footer: {
    tagline:
      "YASHIRIN CAMERA - 2013 yildan beri optom va chakana savdo. Toshkent shahar, Olmazor tumani. Yashirin kameralar, GPS proslushka, diktofon va mikro naushniklar.",
    columns: [
      {
        title: "Katalog",
        links: [
          { label: "Yashirin kameralar", href: "#katalog" },
          { label: "GPS proslushka", href: "#detektorlar" },
          { label: "Diktofonlar", href: "#mahsulotlar" },
          { label: "Mikro naushnik", href: "#mahsulotlar" },
        ],
      },
      {
        title: "Ma'lumot",
        links: [
          { label: "Yetkazib berish", href: "#narxlar" },
          { label: "To'lov usullari", href: "#narxlar" },
          { label: "Kafolat", href: "#narxlar" },
          { label: "Maqolalar", href: "#maqolalar" },
        ],
      },
      {
        title: "Yordam",
        links: [
          { label: "Qanday buyurtma beriladi", href: "#imkoniyatlar" },
          { label: "Savol-javob", href: "#maqolalar" },
          { label: "Do'kon", href: "#mahsulotlar" },
          { label: "Aloqa", href: "#aloqa" },
        ],
      },
    ],
    contactsTitle: "Aloqa",
    addressLabel: "Manzil",
    serviceLabel: "Servis (o'rnatish va sozlash)",
    hours: "Yetkazib berish: O'zbekiston bo'ylab 1-2 kun, jami 98 ta davlatga",
    rights: "Barcha huquqlar himoyalangan.",
    legal: ["Maxfiylik siyosati", "Foydalanish shartlari", "Cookie siyosati"],
  },
}
